/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import POJO.nguoiChoi;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class frm_Menu extends javax.swing.JFrame {

    
    nguoiChoi nguoi;
    frm_DangNhap dn = new frm_DangNhap();
    public frm_Menu() {
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Game Ô Ăn Quan");
    }

    public frm_Menu(nguoiChoi nc) {
        this();
        this.nguoi = nc; // Nhận dữ liệu người chơi từ frm_DangNhap
        if (nguoi != null && nguoi.getTenNguoiChoi() != null) {
            btnDangNhap.setText(nguoi.getTenNguoiChoi()); // Hiển thị tên người chơi đã đăng nhập
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDangNhap = new javax.swing.JButton();
        btnChoiVSMay = new javax.swing.JButton();
        ChoiVSNguoi = new javax.swing.JButton();
        btnXepHang = new javax.swing.JButton();
        AnhNen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDangNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 146, 49));

        btnChoiVSMay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnChoiVSMay.setText("Chơi với máy");
        btnChoiVSMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoiVSMayActionPerformed(evt);
            }
        });
        getContentPane().add(btnChoiVSMay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 146, 53));

        ChoiVSNguoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChoiVSNguoi.setText("Chơi 2 người");
        ChoiVSNguoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoiVSNguoiActionPerformed(evt);
            }
        });
        getContentPane().add(ChoiVSNguoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 146, 49));

        btnXepHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXepHang.setText("Bảng xếp hạng");
        btnXepHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXepHangActionPerformed(evt);
            }
        });
        getContentPane().add(btnXepHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 146, 52));

        AnhNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/AnhNen_1.png"))); // NOI18N
        getContentPane().add(AnhNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChoiVSNguoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoiVSNguoiActionPerformed
        // TODO add your handling code here:
         if (!daNhapTen()) {
            JOptionPane.showMessageDialog(this,"Vui lòng đăng nhập trước khi chơi");

        }
        else
         {
            
            frm_Home gui = new frm_Home(nguoi);
            gui.setVisible(true);
            this.dispose(); //
         }
    }//GEN-LAST:event_ChoiVSNguoiActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        
        dn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnChoiVSMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoiVSMayActionPerformed
        // TODO add your handling code here:
        if (daNhapTen() == false) {
            JOptionPane.showMessageDialog(this,"Vui lòng đăng nhập trước khi chơi");
        }
        else
         {
            frm_Home gui = new frm_Home(nguoi);
            gui.setVisible(true);
            this.dispose(); //
         }
    }//GEN-LAST:event_btnChoiVSMayActionPerformed

    private void btnXepHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXepHangActionPerformed
        // TODO add your handling code here:
        frm_BangXepHang bxh = new frm_BangXepHang();
        bxh.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnXepHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Menu().setVisible(true);
            }
        });
    }
    private boolean daNhapTen() {
        return nguoi != null && nguoi.getTenNguoiChoi() != null;
    }
    public void nhapTenNguoiChoi(String ten) {
        
        btnDangNhap.setText(ten);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnhNen;
    private javax.swing.JButton ChoiVSNguoi;
    private javax.swing.JButton btnChoiVSMay;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnXepHang;
    // End of variables declaration//GEN-END:variables
}
