/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.nguoiChoiDAO;
import POJO.dsO;
import POJO.luotThayDoi;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author PC
 */
import POJO.nguoiChoi;
import POJO.o;
import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;
public class frm_Home extends javax.swing.JFrame {

    
    
    nguoiChoi nguoi; 
    dsO list;
    ArrayList<JButton> listBtn;
    ArrayList<luotThayDoi> dsThayDoi = new ArrayList();
    int checkNguoiChoi = 0;
    int soLuongQuanNguoiChoi2 = 0;
    int soLuongQuanNguoiChoi1 = 0;
    
    public frm_Home() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        list = new dsO();
        khoiTao();
        setTitle("Trò chơi Ô Ăn Quan");
    }
    public frm_Home(nguoiChoi nc){
        this();
        this.nguoi = (nc != null) ? nc : new nguoiChoi();// Nhận dữ liệu người chơi từ frm_DangNhap
        
    }
    
    void khoiTao() {
        listBtn = new ArrayList<>();
        listBtn.add(btnDan1);
        listBtn.add(btnDan2);
        listBtn.add(btnDan3);
        listBtn.add(btnDan4);
        listBtn.add(btnDan5);
        listBtn.add(btnQuan2);
        listBtn.add(btnDan6);
        listBtn.add(btnDan7);
        listBtn.add(btnDan8);
        listBtn.add(btnDan9);
        listBtn.add(btnDan10);
        listBtn.add(btnQuan1);
        for (int i = 0; i < 12; i++) {
            if (i == 5 || i == 11) {
                listBtn.get(i).setText("10");
            } else {
                listBtn.get(i).setText("5");
            }
        }
        for (JButton btn : listBtn) {
            System.out.printf(btn.getName() + " ");
        }
        System.out.println("");
        lbQuanNguoiChoi2.setText("0");
        lbQuanNguoiChoi1.setText("0");
        rdNguoiChoi2.setSelected(false);
        rdNguoiChoi1.setSelected(true);
        rdMay.setSelected(true);
        soLuongQuanNguoiChoi2 = soLuongQuanNguoiChoi1 = checkNguoiChoi = 0;
        dsThayDoi.clear();
        rdNguoiChoi2.setText("Lượt của máy");
        jLabel1.setText("Số lượng quân của máy:");
        jLabel2.setText("Số lượng quân của bạn:");
        rdNguoiChoi1.setText("Lượt của bạn");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        btnQuan2 = new javax.swing.JButton();
        btnQuan1 = new javax.swing.JButton();
        rdNguoiChoi2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rdNguoiChoi1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rdMay = new javax.swing.JRadioButton();
        rdNguoi = new javax.swing.JRadioButton();
        lbQuanNguoiChoi2 = new javax.swing.JLabel();
        lbQuanNguoiChoi1 = new javax.swing.JLabel();
        btnDan1 = new javax.swing.JButton();
        btnDan2 = new javax.swing.JButton();
        btnDan3 = new javax.swing.JButton();
        btnDan4 = new javax.swing.JButton();
        btnDan5 = new javax.swing.JButton();
        btnDan10 = new javax.swing.JButton();
        btnDan9 = new javax.swing.JButton();
        btnDan8 = new javax.swing.JButton();
        btnDan6 = new javax.swing.JButton();
        btnDan7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnINew = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnitemThoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setOpaque(false);

        btnQuan2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnQuan2.setForeground(new java.awt.Color(255, 0, 0));
        btnQuan2.setText("10");
        btnQuan2.setBorderPainted(false);
        btnQuan2.setContentAreaFilled(false);
        btnQuan2.setEnabled(false);
        btnQuan2.setFocusPainted(false);
        btnQuan2.setName("Quan2"); // NOI18N

        btnQuan1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnQuan1.setForeground(new java.awt.Color(255, 0, 0));
        btnQuan1.setText("10");
        btnQuan1.setBorderPainted(false);
        btnQuan1.setContentAreaFilled(false);
        btnQuan1.setEnabled(false);
        btnQuan1.setFocusPainted(false);
        btnQuan1.setName("Quan1"); // NOI18N
        btnQuan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuan1ActionPerformed(evt);
            }
        });

        rdNguoiChoi2.setBackground(new java.awt.Color(255, 255, 255));
        rdNguoiChoi2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rdNguoiChoi2.setForeground(new java.awt.Color(153, 0, 0));
        rdNguoiChoi2.setText("Lượt của máy");
        rdNguoiChoi2.setContentAreaFilled(false);
        rdNguoiChoi2.setEnabled(false);
        rdNguoiChoi2.setFocusPainted(false);
        rdNguoiChoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNguoiChoi2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Số lượng quân của máy:");

        rdNguoiChoi1.setBackground(new java.awt.Color(255, 255, 255));
        rdNguoiChoi1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rdNguoiChoi1.setForeground(new java.awt.Color(153, 0, 0));
        rdNguoiChoi1.setSelected(true);
        rdNguoiChoi1.setText("Lượt của bạn");
        rdNguoiChoi1.setContentAreaFilled(false);
        rdNguoiChoi1.setEnabled(false);
        rdNguoiChoi1.setFocusPainted(false);
        rdNguoiChoi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rdNguoiChoi1MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Số lượng quân của bạn:");

        rdMay.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rdMay.setSelected(true);
        rdMay.setText("Chơi với máy");
        rdMay.setContentAreaFilled(false);
        rdMay.setFocusPainted(false);
        rdMay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rdMayMousePressed(evt);
            }
        });
        rdMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMayActionPerformed(evt);
            }
        });

        rdNguoi.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rdNguoi.setText("Chơi với người");
        rdNguoi.setContentAreaFilled(false);
        rdNguoi.setFocusPainted(false);
        rdNguoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rdNguoiMousePressed(evt);
            }
        });
        rdNguoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNguoiActionPerformed(evt);
            }
        });

        lbQuanNguoiChoi2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        lbQuanNguoiChoi1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        btnDan1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnDan1.setText("5");
        btnDan1.setActionCommand("0");
        btnDan1.setBorderPainted(false);
        btnDan1.setContentAreaFilled(false);
        btnDan1.setFocusPainted(false);
        btnDan1.setName("Dan1"); // NOI18N
        btnDan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDan1ActionPerformed(evt);
            }
        });

        btnDan2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnDan2.setText("5");
        btnDan2.setActionCommand("1");
        btnDan2.setBorderPainted(false);
        btnDan2.setContentAreaFilled(false);
        btnDan2.setFocusPainted(false);
        btnDan2.setName("Dan2"); // NOI18N
        btnDan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDan2btnDan1ActionPerformed(evt);
            }
        });

        btnDan3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnDan3.setText("5");
        btnDan3.setActionCommand("2");
        btnDan3.setBorderPainted(false);
        btnDan3.setContentAreaFilled(false);
        btnDan3.setFocusPainted(false);
        btnDan3.setName("Dan3"); // NOI18N
        btnDan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDan3btnDan1ActionPerformed(evt);
            }
        });

        btnDan4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnDan4.setText("5");
        btnDan4.setActionCommand("3");
        btnDan4.setBorderPainted(false);
        btnDan4.setContentAreaFilled(false);
        btnDan4.setFocusPainted(false);
        btnDan4.setName("Dan4"); // NOI18N
        btnDan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDan4btnDan1ActionPerformed(evt);
            }
        });

        btnDan5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnDan5.setText("5");
        btnDan5.setActionCommand("4");
        btnDan5.setBorderPainted(false);
        btnDan5.setContentAreaFilled(false);
        btnDan5.setFocusPainted(false);
        btnDan5.setName("Dan5"); // NOI18N
        btnDan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDan5btnDan1ActionPerformed(evt);
            }
        });

        btnDan10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnDan10.setText("5");
        btnDan10.setActionCommand("10");
        btnDan10.setBorderPainted(false);
        btnDan10.setContentAreaFilled(false);
        btnDan10.setFocusPainted(false);
        btnDan10.setName("Dan10"); // NOI18N
        btnDan10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDan10btnDan1ActionPerformed(evt);
            }
        });

        btnDan9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnDan9.setText("5");
        btnDan9.setActionCommand("9");
        btnDan9.setBorderPainted(false);
        btnDan9.setContentAreaFilled(false);
        btnDan9.setFocusPainted(false);
        btnDan9.setName("Dan9"); // NOI18N
        btnDan9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDan9btnDan1ActionPerformed(evt);
            }
        });

        btnDan8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnDan8.setText("5");
        btnDan8.setActionCommand("8");
        btnDan8.setBorderPainted(false);
        btnDan8.setContentAreaFilled(false);
        btnDan8.setFocusPainted(false);
        btnDan8.setName("Dan8"); // NOI18N
        btnDan8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDan8btnDan1ActionPerformed(evt);
            }
        });

        btnDan6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnDan6.setText("5");
        btnDan6.setActionCommand("6");
        btnDan6.setBorderPainted(false);
        btnDan6.setContentAreaFilled(false);
        btnDan6.setFocusPainted(false);
        btnDan6.setName("Dan6"); // NOI18N
        btnDan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDan6btnDan1ActionPerformed(evt);
            }
        });

        btnDan7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnDan7.setText("5");
        btnDan7.setActionCommand("7");
        btnDan7.setBorderPainted(false);
        btnDan7.setContentAreaFilled(false);
        btnDan7.setFocusPainted(false);
        btnDan7.setName("Dan7"); // NOI18N
        btnDan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDan7btnDan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel2)
                        .addGap(92, 92, 92)
                        .addComponent(lbQuanNguoiChoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel3)
                        .addGap(106, 106, 106)
                        .addComponent(lbQuanNguoiChoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdMay)
                    .addComponent(rdNguoi))
                .addGap(107, 107, 107))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdNguoiChoi2)
                    .addComponent(rdNguoiChoi1)
                    .addComponent(btnQuan1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDan10, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(btnDan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDan9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDan2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDan3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDan8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDan7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(116, 116, 116)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDan5)
                    .addComponent(btnDan6))
                .addGap(73, 73, 73)
                .addComponent(btnQuan2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(rdNguoiChoi2))
                    .addComponent(lbQuanNguoiChoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnDan1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDan3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDan4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDan2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDan5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnDan9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDan8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDan10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDan7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDan6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(rdMay)
                        .addGap(18, 18, 18)
                        .addComponent(rdNguoi)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbQuanNguoiChoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(109, 109, 109))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuan1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuan2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addComponent(rdNguoiChoi1)
                .addGap(166, 166, 166))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel2, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RES/background.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jMenu2.setText("Trò chơi");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        mnINew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnINew.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mnINew.setText("Trò chơi mới");
        mnINew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnINewActionPerformed(evt);
            }
        });
        jMenu2.add(mnINew);
        jMenu2.add(jSeparator1);

        mnitemThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnitemThoat.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        mnitemThoat.setText("Thoát");
        mnitemThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemThoatActionPerformed(evt);
            }
        });
        jMenu2.add(mnitemThoat);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    
    private void rdNguoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNguoiActionPerformed
        // TODO add your handling code here:
        rdNguoiChoi2.setText("Lượt của người chơi 2");
        rdNguoiChoi1.setText("Lượt của người chơi 1");
        jLabel1.setText("Số lượng quân của người chơi 2:");
        jLabel2.setText("Số lượng quân của người chơi 1:");
    }//GEN-LAST:event_rdNguoiActionPerformed

    private void rdNguoiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdNguoiMousePressed
        // TODO add your handling code here:
        rdNguoiChoi2.setText("Lượt của người chơi 2");
        rdNguoiChoi1.setText("Lượt của người chơi 1");
        jLabel1.setText("Số lượng quân của người chơi 2:");
        jLabel2.setText("Số lượng quân của người chơi 1:");
    }//GEN-LAST:event_rdNguoiMousePressed

    private void rdMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMayActionPerformed
        // TODO add your handling code here:
        rdNguoiChoi2.setText("Lượt của máy");
        rdNguoiChoi1.setText("Lượt của bạn");
        jLabel1.setText("Số lượng quân của máy:");
        jLabel2.setText("Số lượng quân của bạn:");
    }//GEN-LAST:event_rdMayActionPerformed

    private void rdMayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdMayMousePressed
        // TODO add your handling code here:
        rdNguoiChoi2.setText("Lượt của máy");
        rdNguoiChoi1.setText("Lượt của bạn");
        jLabel1.setText("Số lượng quân của máy:");
        jLabel2.setText("Số lượng quân của bạn:");

    }//GEN-LAST:event_rdMayMousePressed

    private void rdNguoiChoi1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdNguoiChoi1MousePressed
        // TODO add your handling code here:
        return;
    }//GEN-LAST:event_rdNguoiChoi1MousePressed

    private void rdNguoiChoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNguoiChoi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNguoiChoi2ActionPerformed

    private void btnQuan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuan1ActionPerformed

    private void btnDan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDan1ActionPerformed
        // TODO add your handling code here:
        int thuTuO = Integer.parseInt(evt.getActionCommand());
        if (!ktraNguoiChoi(thuTuO)) {
            return;
        }
        Object[] option = {"Trái", "Phải", "Huỷ"};
        int choose = JOptionPane.showOptionDialog(null, "Bạn muốn đi hướng nào?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, 1);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.YES_OPTION) {
            boolean checkHuong = true;
            if (choose == JOptionPane.NO_OPTION) {
                checkHuong = false;
            }
            try {
                run(thuTuO, checkHuong);
                if (!ktraTranKetThuc() && rdMay.isSelected()) {
                    runAI();
                    ktraTranKetThuc();
                }
                thayDoi();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi " + evt.getActionCommand(), "Thông báo", 1);
            }
        }
    }//GEN-LAST:event_btnDan1ActionPerformed

    private void btnDan2btnDan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDan2btnDan1ActionPerformed
        // TODO add your handling code here:
        int thuTuO = Integer.parseInt(evt.getActionCommand());
        if (!ktraNguoiChoi(thuTuO)) {
            return;
        }
        Object[] option = {"Trái", "Phải", "Huỷ"};
        int choose = JOptionPane.showOptionDialog(null, "Bạn muốn đi hướng nào?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, 1);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.YES_OPTION) {
            boolean checkHuong = true;
            if (choose == JOptionPane.NO_OPTION) {
                checkHuong = false;
            }
            try {
                run(thuTuO, checkHuong);
                if (!ktraTranKetThuc() && rdMay.isSelected()) {
                    runAI();
                    ktraTranKetThuc();
                }
                thayDoi();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi " + evt.getActionCommand(), "Thông báo", 1);
            }
        }
    }//GEN-LAST:event_btnDan2btnDan1ActionPerformed

    private void btnDan3btnDan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDan3btnDan1ActionPerformed
        // TODO add your handling code here:
        int thuTuO = Integer.parseInt(evt.getActionCommand());
        if (!ktraNguoiChoi(thuTuO)) {
            return;
        }
        Object[] option = {"Trái", "Phải", "Huỷ"};
        int choose = JOptionPane.showOptionDialog(null, "Bạn muốn đi hướng nào?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, 1);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.YES_OPTION) {
            boolean checkHuong = true;
            if (choose == JOptionPane.NO_OPTION) {
                checkHuong = false;
            }
            try {
                run(thuTuO, checkHuong);
                if (!ktraTranKetThuc() && rdMay.isSelected()) {
                    runAI();
                    ktraTranKetThuc();
                }
                thayDoi();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi " + evt.getActionCommand(), "Thông báo", 1);
            }
        }
    }//GEN-LAST:event_btnDan3btnDan1ActionPerformed

    private void btnDan4btnDan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDan4btnDan1ActionPerformed
        // TODO add your handling code here:
        int thuTuO = Integer.parseInt(evt.getActionCommand());
        if (!ktraNguoiChoi(thuTuO)) {
            return;
        }
        Object[] option = {"Trái", "Phải", "Huỷ"};
        int choose = JOptionPane.showOptionDialog(null, "Bạn muốn đi hướng nào?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, 1);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.YES_OPTION) {
            boolean checkHuong = true;
            if (choose == JOptionPane.NO_OPTION) {
                checkHuong = false;
            }
            try {
                run(thuTuO, checkHuong);
                if (!ktraTranKetThuc() && rdMay.isSelected()) {
                    runAI();
                    ktraTranKetThuc();
                }
                thayDoi();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi " + evt.getActionCommand(), "Thông báo", 1);
            }
        }
    }//GEN-LAST:event_btnDan4btnDan1ActionPerformed

    private void btnDan5btnDan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDan5btnDan1ActionPerformed
        // TODO add your handling code here:
        int thuTuO = Integer.parseInt(evt.getActionCommand());
        if (!ktraNguoiChoi(thuTuO)) {
            return;
        }
        Object[] option = {"Trái", "Phải", "Huỷ"};
        int choose = JOptionPane.showOptionDialog(null, "Bạn muốn đi hướng nào?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, 1);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.YES_OPTION) {
            boolean checkHuong = true;
            if (choose == JOptionPane.NO_OPTION) {
                checkHuong = false;
            }
            try {
                run(thuTuO, checkHuong);
                if (!ktraTranKetThuc() && rdMay.isSelected()) {
                    runAI();
                    ktraTranKetThuc();
                }
                thayDoi();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi " + evt.getActionCommand(), "Thông báo", 1);
            }
        }
    }//GEN-LAST:event_btnDan5btnDan1ActionPerformed

    private void btnDan10btnDan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDan10btnDan1ActionPerformed
        // TODO add your handling code here:
        int thuTuO = Integer.parseInt(evt.getActionCommand());
        if (!ktraNguoiChoi(thuTuO)) {
            return;
        }
        Object[] option = {"Trái", "Phải", "Huỷ"};
        int choose = JOptionPane.showOptionDialog(null, "Bạn muốn đi hướng nào?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, 1);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.YES_OPTION) {
            boolean checkHuong = true;
            if (choose == JOptionPane.NO_OPTION) {
                checkHuong = false;
            }
            try {
                run(thuTuO, checkHuong);
                if (!ktraTranKetThuc() && rdMay.isSelected()) {
                    runAI();
                    ktraTranKetThuc();
                }
                thayDoi();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi " + evt.getActionCommand(), "Thông báo", 1);
            }
        }
    }//GEN-LAST:event_btnDan10btnDan1ActionPerformed

    private void btnDan9btnDan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDan9btnDan1ActionPerformed
        // TODO add your handling code here:
        int thuTuO = Integer.parseInt(evt.getActionCommand());
        if (!ktraNguoiChoi(thuTuO)) {
            return;
        }
        Object[] option = {"Trái", "Phải", "Huỷ"};
        int choose = JOptionPane.showOptionDialog(null, "Bạn muốn đi hướng nào?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, 1);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.YES_OPTION) {
            boolean checkHuong = true;
            if (choose == JOptionPane.NO_OPTION) {
                checkHuong = false;
            }
            try {
                run(thuTuO, checkHuong);
                if (!ktraTranKetThuc() && rdMay.isSelected()) {
                    runAI();
                    ktraTranKetThuc();
                }
                thayDoi();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi " + evt.getActionCommand(), "Thông báo", 1);
            }
        }
    }//GEN-LAST:event_btnDan9btnDan1ActionPerformed

    private void btnDan8btnDan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDan8btnDan1ActionPerformed
        // TODO add your handling code here:
        int thuTuO = Integer.parseInt(evt.getActionCommand());
        if (!ktraNguoiChoi(thuTuO)) {
            return;
        }
        Object[] option = {"Trái", "Phải", "Huỷ"};
        int choose = JOptionPane.showOptionDialog(null, "Bạn muốn đi hướng nào?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, 1);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.YES_OPTION) {
            boolean checkHuong = true;
            if (choose == JOptionPane.NO_OPTION) {
                checkHuong = false;
            }
            try {
                run(thuTuO, checkHuong);
                if (!ktraTranKetThuc() && rdMay.isSelected()) {
                    runAI();
                    ktraTranKetThuc();
                }
                thayDoi();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi " + evt.getActionCommand(), "Thông báo", 1);
            }
        }
    }//GEN-LAST:event_btnDan8btnDan1ActionPerformed

    private void btnDan6btnDan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDan6btnDan1ActionPerformed
        // TODO add your handling code here:
        int thuTuO = Integer.parseInt(evt.getActionCommand());
        if (!ktraNguoiChoi(thuTuO)) {
            return;
        }
        Object[] option = {"Trái", "Phải", "Huỷ"};
        int choose = JOptionPane.showOptionDialog(null, "Bạn muốn đi hướng nào?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, 1);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.YES_OPTION) {
            boolean checkHuong = true;
            if (choose == JOptionPane.NO_OPTION) {
                checkHuong = false;
            }
            try {
                run(thuTuO, checkHuong);
                if (!ktraTranKetThuc() && rdMay.isSelected()) {
                    runAI();
                    ktraTranKetThuc();
                }
                thayDoi();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi " + evt.getActionCommand(), "Thông báo", 1);
            }
        }
    }//GEN-LAST:event_btnDan6btnDan1ActionPerformed

    private void btnDan7btnDan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDan7btnDan1ActionPerformed
        // TODO add your handling code here:
        int thuTuO = Integer.parseInt(evt.getActionCommand());
        if (!ktraNguoiChoi(thuTuO)) {
            return;
        }
        Object[] option = {"Trái", "Phải", "Huỷ"};
        int choose = JOptionPane.showOptionDialog(null, "Bạn muốn đi hướng nào?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, 1);
        if (choose == JOptionPane.NO_OPTION || choose == JOptionPane.YES_OPTION) {
            boolean checkHuong = true;
            if (choose == JOptionPane.NO_OPTION) {
                checkHuong = false;
            }
            try {
                run(thuTuO, checkHuong);
                if (!ktraTranKetThuc() && rdMay.isSelected()) {
                    runAI();
                    ktraTranKetThuc();
                }
                thayDoi();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Lỗi " + evt.getActionCommand(), "Thông báo", 1);
            }
        }
    }//GEN-LAST:event_btnDan7btnDan1ActionPerformed

    private void mnINewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnINewActionPerformed
        // TODO add your handling code here:
        list = new dsO();
        khoiTao();
    }//GEN-LAST:event_mnINewActionPerformed

    private void mnitemThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnitemThoatActionPerformed

     void run(int thuTuO, boolean checkHuong) {
        int soLuongDa = 0;
        soLuongDa = list.getList().get(thuTuO).getSoLuongDa();
        int oBatDau = 0;
        do {
            String tenO = list.getList().get(thuTuO).getTenO();
            int soDaBD = 0;
            list.getList().set(thuTuO, new o(tenO, 0));
            dsThayDoi.add(new luotThayDoi(thuTuO, 0));
            if ((thuTuO < 5 && checkHuong) || (thuTuO > 5 && !checkHuong)) {
                oBatDau = thuTuO - 1;
            } else if ((thuTuO < 5 && !checkHuong) || (thuTuO > 5 && checkHuong)) {
                oBatDau = thuTuO + 1;
            }
            while (soLuongDa > 0) {
                if (oBatDau < 0) {
                    oBatDau = 11;
                } else if (oBatDau > 11) {
                    oBatDau = 0;
                }
                tenO = list.getList().get(oBatDau).getTenO();
                soDaBD = list.getList().get(oBatDau).getSoLuongDa();
                list.getList().set(oBatDau, new o(tenO, soDaBD + 1));
                dsThayDoi.add(new luotThayDoi(oBatDau, soDaBD + 1));
                if ((thuTuO < 5 && checkHuong) || (thuTuO > 5 && !checkHuong)) {
                    oBatDau--;
                } else if ((thuTuO < 5 && !checkHuong) || (thuTuO > 5 && checkHuong)) {
                    oBatDau++;
                }

                soLuongDa--;
            }
            if (oBatDau < 0) {
                oBatDau = 11;
            } else if (oBatDau > 11) {
                oBatDau = 0;
            }
            if (oBatDau == 11 || oBatDau == 5) {
                break;
            }
            if (list.getList().get(oBatDau).getSoLuongDa() != 0) {
                if (checkHuong) {
                    if ((thuTuO > 5 && oBatDau < 5) || (thuTuO < 5 && oBatDau > 5)) {
                        checkHuong = false;
                    }
                } else {
                    if ((thuTuO > 5 && oBatDau < 5) || (thuTuO < 5 && oBatDau > 5)) {
                        checkHuong = true;
                    }
                }
                soLuongDa = list.getList().get(oBatDau).getSoLuongDa();
                thuTuO = oBatDau;
            } else {
                break;
            }
        } while (true);
        
        while (true) {
            if (list.getList().get(oBatDau).getSoLuongDa() == 0) {
                if ((thuTuO < 5 && checkHuong) || (thuTuO > 5 && !checkHuong)) {
                    oBatDau--;
                } else if ((thuTuO < 5 && !checkHuong) || (thuTuO > 5 && checkHuong)) {
                    oBatDau++;
                }
                if (oBatDau < 0) {
                    oBatDau = 11;
                } else if (oBatDau > 11) {
                    oBatDau = 0;
                }
                int quanAn = list.getList().get(oBatDau).getSoLuongDa();
                if (checkNguoiChoi % 2 == 0) {
                    soLuongQuanNguoiChoi1 += quanAn;
                } else {
                    soLuongQuanNguoiChoi2 += quanAn;
                }
                String tenO = list.getList().get(oBatDau).getTenO();
                list.getList().set(oBatDau, new o(tenO, 0));
                dsThayDoi.add(new luotThayDoi(oBatDau, 0));
                if (quanAn != 0) {
                    if ((thuTuO < 5 && checkHuong) || (thuTuO > 5 && !checkHuong)) {
                        oBatDau--;
                    } else if ((thuTuO < 5 && !checkHuong) || (thuTuO > 5 && checkHuong)) {
                        oBatDau++;
                    }
                    if (oBatDau < 0) {
                        oBatDau = 11;
                    } else if (oBatDau > 11) {
                        oBatDau = 0;
                    }

                } else {
                    break;
                }
            } else {
                break;
            }
        }
        checkNguoiChoi++;
    }
    void runAI() {
        int vt = 0;
        int max = 0, trai, phai;
        boolean checkHuong = true;
        ArrayList<o> lst;
        for (int i = 0; i < 5; i++) {
            lst = copy();
            trai = checkAI(lst, i, true);
            lst = copy();
            phai = checkAI(lst, i, false);
            if (max <= trai) {
                max = trai;
                vt = i;
                checkHuong = true;
            }
            if (max <= phai) {
                vt = i;
                checkHuong = false;
                max = phai;
            }
        }
        System.out.println(vt + " " + checkHuong + " " + max);
        run(vt, checkHuong);
    }

    int checkAI(ArrayList<o> lst, int thuTuO, boolean checkHuong) {
        int soLuongDa = 0;
        int soQuanAn = 0;
        soLuongDa = lst.get(thuTuO).getSoLuongDa();
        if (soLuongDa == 0) {
            return -1;
        }
        int oBatDau = 0;
        do {
            String tenO = lst.get(thuTuO).getTenO();
            int soDaBD = 0;
            lst.set(thuTuO, new o(tenO, 0));
            if ((thuTuO < 5 && checkHuong) || (thuTuO > 5 && !checkHuong)) {
                oBatDau = thuTuO - 1;
            } else if ((thuTuO < 5 && !checkHuong) || (thuTuO > 5 && checkHuong)) {
                oBatDau = thuTuO + 1;
            }
            while (soLuongDa > 0) {
                if (oBatDau < 0) {
                    oBatDau = 11;
                } else if (oBatDau > 11) {
                    oBatDau = 0;
                }
                tenO = lst.get(oBatDau).getTenO();
                soDaBD = lst.get(oBatDau).getSoLuongDa();
                lst.set(oBatDau, new o(tenO, soDaBD + 1));
                if ((thuTuO < 5 && checkHuong) || (thuTuO > 5 && !checkHuong)) {
                    oBatDau--;
                } else if ((thuTuO < 5 && !checkHuong) || (thuTuO > 5 && checkHuong)) {
                    oBatDau++;
                }

                soLuongDa--;
            }
            if (oBatDau < 0) {
                oBatDau = 11;
            } else if (oBatDau > 11) {
                oBatDau = 0;
            }
            if (oBatDau == 11 || oBatDau == 5) {
                break;
            }

            if (lst.get(oBatDau).getSoLuongDa() != 0) {
                if (checkHuong) {
                    if ((thuTuO > 5 && oBatDau < 5) || (thuTuO < 5 && oBatDau > 5)) {
                        checkHuong = false;
                    }
                } else {
                    if ((thuTuO > 5 && oBatDau < 5) || (thuTuO < 5 && oBatDau > 5)) {
                        checkHuong = true;
                    }
                }
                soLuongDa = lst.get(oBatDau).getSoLuongDa();
                thuTuO = oBatDau;
            } else {
                break;
            }
        } while (true);
        while (true) {
            if (lst.get(oBatDau).getSoLuongDa() == 0) {
                if ((thuTuO < 5 && checkHuong) || (thuTuO > 5 && !checkHuong)) {
                    oBatDau--;
                } else if ((thuTuO < 5 && !checkHuong) || (thuTuO > 5 && checkHuong)) {
                    oBatDau++;
                }
                if (oBatDau < 0) {
                    oBatDau = 11;
                } else if (oBatDau > 11) {
                    oBatDau = 0;
                }
                int quanAn = lst.get(oBatDau).getSoLuongDa();
                soQuanAn += quanAn;
                String tenO = lst.get(oBatDau).getTenO();
                lst.set(oBatDau, new o(tenO, 0));
                if (quanAn != 0) {
                    if ((thuTuO < 5 && checkHuong) || (thuTuO > 5 && !checkHuong)) {
                        oBatDau--;
                    } else if ((thuTuO < 5 && !checkHuong) || (thuTuO > 5 && checkHuong)) {
                        oBatDau++;
                    }
                    if (oBatDau < 0) {
                        oBatDau = 11;
                    } else if (oBatDau > 11) {
                        oBatDau = 0;
                    }
                } else {
                    break;
                }
            } else {
                break;
            }
        }
        return soQuanAn;
    }

    ArrayList<o> copy() {
        ArrayList<o> lst = new ArrayList();
        for (int i = 0; i < 12; i++) {
            lst.add(list.getList().get(i));
        }
        return lst;
    }

    int tongDaNguoiChoi2() {
        int sum = 0;
        for (int i = 0; i < 5; i++) {
            sum += list.getList().get(i).getSoLuongDa();
        }
        return sum;
    }

    int tongDaNguoiChoi1() {
        int sum = 0;
        for (int i = 6; i < 11; i++) {
            sum += list.getList().get(i).getSoLuongDa();
        }
        return sum;
    }

    void reset() {

        for (int i = 0; i < 12; i++) {
            if (list.getList().get(i).getSoLuongDa() != 0) {
                String tenO = list.getList().get(i).getTenO();
                list.getList().set(i, new o(tenO, 0));
                dsThayDoi.add(new luotThayDoi(i, 0));
            }
        }
    }

    boolean ktraTranKetThuc() {
        if (list.getList().get(5).getSoLuongDa() == 0 && list.getList().get(11).getSoLuongDa() == 0) {
            soLuongQuanNguoiChoi2 = soLuongQuanNguoiChoi2 + tongDaNguoiChoi2();
            soLuongQuanNguoiChoi1 = soLuongQuanNguoiChoi1 + tongDaNguoiChoi1();
            reset();
            return true;
        }
        if (list.getList().get(5).getSoLuongDa() != 0 || list.getList().get(11).getSoLuongDa() != 0) {
            if (checkNguoiChoi % 2 != 0 && tongDaNguoiChoi2() == 0) {
                if (soLuongQuanNguoiChoi2 < 5) {
                    return true;
                }
                for (int i = 0; i < 5; i++) {
                    String tenO = list.getList().get(i).getTenO();
                    list.getList().set(i, new o(tenO, 1));
                    dsThayDoi.add(new luotThayDoi(i, 1));
                }
                soLuongQuanNguoiChoi2 = soLuongQuanNguoiChoi2 - 5;
            }
            if (checkNguoiChoi % 2 == 0 && tongDaNguoiChoi1() == 0) {
                if (soLuongQuanNguoiChoi1 < 5) {
                    return true;
                }
                for (int i = 6; i < 11; i++) {
                    String tenO = list.getList().get(i).getTenO();
                    list.getList().set(i, new o(tenO, 1));
                    dsThayDoi.add(new luotThayDoi(i, 1));
                }
                soLuongQuanNguoiChoi1 = soLuongQuanNguoiChoi1 - 5;
            }
        }
        return false;
    }

int nguoiThang() {
    if (ktraTranKetThuc()) {
        nguoi.setSoTranDaChoi(nguoi.getSoTranDaChoi() + 1); // Cập nhật số trận đã chơi

        if (soLuongQuanNguoiChoi2 == soLuongQuanNguoiChoi1) {
            // Trận hòa
            boolean kq = nguoiChoiDAO.capNhatSoTran(nguoi);
            boolean kq1 = nguoiChoiDAO.capNhatSTiLeThang(nguoi);
            System.out.println(kq);
            System.out.println(kq1);
            return 0; // hòa
        } else if (soLuongQuanNguoiChoi1 > soLuongQuanNguoiChoi2) {
            // Người chơi 1 thắng
            nguoi.setSoTranThang(nguoi.getSoTranThang() + 1);
            boolean kq = nguoiChoiDAO.capNhatSoTran(nguoi);
            boolean kq1 = nguoiChoiDAO.capNhatSoTranThang(nguoi);
            boolean kq2 = nguoiChoiDAO.capNhatSTiLeThang(nguoi);
            System.out.println(kq);
            System.out.println(kq1);
            System.out.println(kq2);
            return 1; // Người chơi 1 thắng
        } else {
            // Người chơi 2 thắng
            boolean kq = nguoiChoiDAO.capNhatSoTran(nguoi);
            boolean kq1 = nguoiChoiDAO.capNhatSTiLeThang(nguoi);
            System.out.println(kq);
            System.out.println(kq1);
            return -1; // Người chơi 2 thắng
        }
    }
    return 2; // Trận chưa kết thúc
}

    void win() {
    int xacDinhThangThua = nguoiThang();
    if (xacDinhThangThua == 2) {
        return; // Trận đấu chưa kết thúc
    }

    // Cập nhật cơ sở dữ liệu nếu đấu với máy
    if (rdMay.isSelected()) {
        // Cập nhật số trận đã chơi
        nguoi.setSoTranDaChoi(nguoi.getSoTranDaChoi() + 1);
        boolean updateSoTran = nguoiChoiDAO.capNhatSoTran(nguoi);
        if (!updateSoTran) {
            JOptionPane.showMessageDialog(null, "Lỗi cập nhật số trận đã chơi", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Trường hợp hòa
        if (xacDinhThangThua == 0) {
            boolean updateTiLeThang = nguoiChoiDAO.capNhatSTiLeThang(nguoi);
            if (!updateTiLeThang) {
                JOptionPane.showMessageDialog(null, "Lỗi cập nhật tỷ lệ thắng", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
            JOptionPane.showMessageDialog(null, "Hoà", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Trường hợp người chơi thắng
        if (xacDinhThangThua == 1) {
            nguoi.setSoTranThang(nguoi.getSoTranThang() + 1);
            boolean updateSoTranThang = nguoiChoiDAO.capNhatSoTranThang(nguoi);
            boolean updateTiLeThang = nguoiChoiDAO.capNhatSTiLeThang(nguoi);
            if (!updateSoTranThang || !updateTiLeThang) {
                JOptionPane.showMessageDialog(null, "Lỗi cập nhật dữ liệu thắng", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }

    // Hiển thị thông báo kết quả
    if (xacDinhThangThua == 0) {
        JOptionPane.showMessageDialog(null, "Hoà", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    } else {
        String xdNguoiChoi = "";
        if (rdMay.isSelected() && xacDinhThangThua == -1) {
            xdNguoiChoi = "Máy";
        } else if (xacDinhThangThua == 1) {
            if (rdMay.isSelected()) {
                xdNguoiChoi = "Bạn";
            } else {
                xdNguoiChoi = "Người chơi 1";
            }
        } else if (xacDinhThangThua == -1) {
            xdNguoiChoi = "Người chơi 2";
        }
        JOptionPane.showMessageDialog(null, xdNguoiChoi + " đã thắng", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }
}


    void thayDoi() {

        new Thread() {
            @Override
            public void run() {
                try {
                    int j = 0;
                    if (rdMay.isSelected()) {
                        if (rdNguoiChoi1.isSelected()) {
                            rdNguoiChoi2.setSelected(true);
                        } else {
                            rdNguoiChoi1.setSelected(true);
                        }
                    }
                    while (true) {
                        sleep(500);
                        if (j >= dsThayDoi.size()) {
                            break;
                        }
                        listBtn.get(dsThayDoi.get(j).getViTri()).setText(dsThayDoi.get(j).getSoLuongDa() + "");
                        j++;
                    }
                    dsThayDoi.clear();

                    if (rdNguoiChoi1.isSelected()) {
                        rdNguoiChoi2.setSelected(true);
                    } else {
                        rdNguoiChoi1.setSelected(true);
                    }

                    lbQuanNguoiChoi2.setText(soLuongQuanNguoiChoi2 + "");
                    lbQuanNguoiChoi1.setText(soLuongQuanNguoiChoi1 + "");
                    win();
                } catch (InterruptedException e) {
                }
            }
        }.start();

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Home().setVisible(true);
            }
        });
    }
    boolean ktraNguoiChoi(int thuTuO) {
        if (list.getList().get(thuTuO).getSoLuongDa() == 0) {
            return false;
        }
        if (checkNguoiChoi % 2 == 0) {
            switch (thuTuO) {
                case 0:
                case 1:
                case 2:
                case 3:
                case 4:
                    JOptionPane.showMessageDialog(null, "Bạn không được đi ô này", "Thông báo", 1);
                    return false;
            }
        } else {
            switch (thuTuO) {
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                    JOptionPane.showMessageDialog(null, "Bạn không được đi ô này", "Thông báo", 1);
                    return false;
            }
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDan1;
    private javax.swing.JButton btnDan10;
    private javax.swing.JButton btnDan2;
    private javax.swing.JButton btnDan3;
    private javax.swing.JButton btnDan4;
    private javax.swing.JButton btnDan5;
    private javax.swing.JButton btnDan6;
    private javax.swing.JButton btnDan7;
    private javax.swing.JButton btnDan8;
    private javax.swing.JButton btnDan9;
    private javax.swing.JButton btnQuan1;
    private javax.swing.JButton btnQuan2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbQuanNguoiChoi1;
    private javax.swing.JLabel lbQuanNguoiChoi2;
    private javax.swing.JMenuItem mnINew;
    private javax.swing.JMenuItem mnitemThoat;
    private javax.swing.JRadioButton rdMay;
    private javax.swing.JRadioButton rdNguoi;
    private javax.swing.JRadioButton rdNguoiChoi1;
    private javax.swing.JRadioButton rdNguoiChoi2;
    // End of variables declaration//GEN-END:variables
}
